---
kind: pipeline
name: default

steps:

- name: audit
  image: node:12
  commands: ['npm audit --package-json-only --audit-level=moderate']
            
- name: install
  image: node:12
  commands: ['npm ci --ignore-scripts']

- name: test
  image: node:12
  commands: ['npm test']

- name: build
  image: node:12
  commands: ['npm run build']

- name: static-security-scan
  image: quay.io/natlibfi/nodejsscan
  commands: ['python /usr/src/app/cli.py -d dist']

- name: npm-publish
  image: plugins/npm
  settings:
    registry: 'https://registry.npmjs.org/'
    token:
      from_secret: npm_token
  when:
    event: tag   
---
kind: secret
name: npm_token
data: 57r1iBfIVFGrmpGB+wayB9QvaSRFFNtnohL1IKLT5isAsCIlSzOcYv4NWdPijJTnL7vzoFpD/h75U9N5pKM9cA==
---
kind: signature
hmac: f81dafb1d474d531b0bfc5f693180014f77c8a8e706d225335a95a1e837c6b9f

...
