---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push
    - tag

steps:

  - name: audit
    image: node:14
    commands:
      - npm audit --package-lock-only --production --audit-level=moderate

  - name: install
    image: node:14
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true
    commands:
      - npm install -g npm@latest
      - npm ci

  - name: test
    image: node:14
    commands:
      - npm test

  - name: check-coverage
    image: node:14
    commands:
      - npm run coverage

  - name: build
    image: node:14
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true
    commands:
      - npm install -g npm@latest
      - npm run build
      - npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: npm
    image: plugins/npm
    settings:
      registry: 'https://registry.npmjs.org/'
      token:
        from_secret: npm_token
    when:
      event: tag
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: npm_token
data: 57r1iBfIVFGrmpGB+wayB9QvaSRFFNtnohL1IKLT5isAsCIlSzOcYv4NWdPijJTnL7vzoFpD/h75U9N5pKM9cA==
---
kind: secret
name: ssh_key
data: j1lhcPRrQX1hvJKHN+5sV0TGLi4wxYFaPDc9g8CvblpM4qSG/51RKfs5boj5EdFmBlzDDzOhrjvScCZA+j4UUsyUVlGMhjWGpq4gSZwfZT8Eg9Z4vDBf44ZhjR0tCVsBZ3qXs18SGn1HhcN2DszmkSLebPnBQ2CwxLa6Wt0OgPp/g+B3yJJ5r/k6lgcgR8Zt2InknVLfY4Nb0LOft8d8zipuZDoxK5xkb+vdrrMUb6UlgAZMd7NX4Zk0fgoJeVkSGkx2FK019rpjsSfAoXUqDBjY3PG+Y2Z43y3yDGiCxxUNrfN2km0Hxzi/gHZ0dVlNhP59td0TCLPurXzb+dkXI3R91EbIiCdEs6ZdlQQd00uJMTmJqs+BasnjIGlY7NCNbBIvJtxIPMUdlKkhUkfh+ybhHfZenXGu8obcD+xxgXL/vWfONAuf/4RojkveBD4U6whzicOpDCXMI7hXEibgktOYXmyUcR/K70ujnVCTW9gTkzdgQ/1C8CwiEu4s0Mh0tIxc12SYT6YHhGGvKMqRRHuQCg5ACLr3Jvsi7dRAaMGq/MLCFMXQRJn+HBeTc0y/7vzGDbeE8kN2JLcIMZ8Fig8ZJGxTxq4DfeAsLqJdY7AWeN5cLdvvAPL4bi0udBd9FsRPzsuUdMkOXlPAn+CCdxhpYBOqzKlAuSMwuLpsvJQp6IDr1d2XCb4df5H7yBdNhGHvdmr8q59QX7hvHErJtXIv9lqyAo2gCR2NA1N0uaB07M0cKYlOXZ7a9B4bx3fMQa+Sd7OsUWB5qQM2WhUHbHkBtC9VN20rI2XQNtbd5KH/Xik0shOkjH/yTtGHf4wefCnaT/ZPY4PZ5iGncyjg1an4Y/3eH8oFBP27iGfUVY7MNVO1YyV4tV6YuYTCNxRibEBE2T17Xf4niJ4yR3nDoUVC9SZqvq+QKV1DD8CZQHMDRzp3OXZR6nwtDSLXGfN4e/NGeeYXgS7seHAG6XpKXTm1J/qenPd++a0xkqWrp/IR71E9+a8qXRKdc9Ww2sj1bn9Np3WYdZSrnDjUvd+s2JKFb0+MKwKgPZR94iVfpdxDTeRRPjEzRJGlfsVF7imIJxsT/OpZkk4zrlI1HcBUg8sbLFyexg1S2WsCtTNt6MydCg6wGtGst0dniJWfO232+z0LooLjswJezTKKnlsSOrGNvhdqhCN5v7vyJL18kmjPtgvouyOj7/HWjkWoGOe6Vl7DS8ed+IgDvU7IggmOYh7mKcE7GUMmqfu7m1D0StAqKnvBIT8Ky3ufCfTXWE3zW7/fRW/eSo3wK6EpMdzZiQTdBLS7Q0F+OmmnTWTryX3hNnQAaShJHbc3p0mFEd/8Emw/w1lxtEdWDfRG5pgQ44njJ7/iEEI2dL/U4fyloc9ZuqoCZf0yWSbmQwAsTAA1xw4BY2Lkrzv0wKiHoMPBWtw8abFysS5O003jW4XCLkRBHsi4JP8WYYKeFUpIIbfF4++UxwDv0y4LiCLJsZcVgFvA8WKaMZM0yVAUjOGtyvH8Mbh+u4Zuo8NwrHyCv/s9bCjowdaAZd0JMKbaw1jTBcn1u2jFaBoRqN+d4fkJvD/0+oNTolQ9qN31IYb7UGThyJ0XzFX89JixweEGdCqAqEWrw7L/JaMV3dZAyaNnClKymwrQq+SmIgXJ4CbC6x9XhyDByZMn17anvplh3+ytpefX5yWD4CXxAKtVOrqrqa2w/Zx5cOCSokS/0E5zjLwChF9cdDGVa0u4esLxTwT4XthDGIMW/Y4kUqB6x7VSArXHBOi96Da7uDLlhox4WFINDhwkM6cUQvQ0USoYJ8axRD6Gh9uiq2SIGATMnfAra+BrDkPZDE4Ip7hJv4AV8Xd9gdqmDr8iN0ffomxDewyPmXaCxPxYVloqtrhG9ZFzu+s0KN6VHmzymQXiKbQIIDpIwfQTkWrKJ/xSHbGkI6YIl+jjxeLK+vCqBm9QnRnUaSpc30J/NiUCc7iCEuL9W5VO2qQL/MK3lAYPNtFRG4ahusKXpzD1e1rIz9Ex76GqrYHqbRM4KxnuZDOu9xBXpAwQ8iCrOeris7M/IJMyPP4Ex1pzwLAGMaSRUoI3lF3SqdA3W0bGKqg7QW+HhV+UXw0JGulVqPFMhQAiaeXPNSBytt3deUx5PjO/jyOfdOS3tWCKtzNBwpB0/SQpgQ6b2imK9HP1UT9FJ1ncSvr5DwHvP+Tciogm0KMYUzba2D+pLWBule7VFTxbLegkkqgnuXmr9kB0xulSyjXGML9k5Xmmf91N6c4m/hNGQ57BqGcCwERSgRiN4BSl4fjDN4/8OHDms3mpTl2j+gHrh4QIXvXhgb+8WJqXmRiqMOVwh8kY75o0nyH0xwTyD3K56rqHGsPUXc0qKg39LZ8/5DHs+AZgNnRYGygBGXOUY3iy5KdJJLxWc4Sb3hTKHhEq6eabXr/AgjW8L8h9mAF9PRXO2bD6Vi3ubjg5JBXVpE6ua0jjI/rxi/DA2vB/Rq5nw6ApGhgVaMx0Mu+d/OcCc6rudLDFJPG0tL+R8W70CE/JYeVjTUPLAyu+WsC0Bq+53GULuuqSpo07nAez+VWS+rCWvEqh6BmEef9fph0mrLrIKCp0QFLrfdfigY6nxW1TPSqmmRtBvohJTF5BPL9kUjXaME2J4itEtaOajpkLJYNyIarwqe19rYacrmE8Yx1dDI+Fniuls78+2zp8BekIPZV532owzFBcnKNWYU1ZuZsHqQsLdo9DJKsU5CK8dY9lUNxsr6B9dOGCEbFQqHAc4UWdfK+1eKQsgJ3hPE3PBZefvdhiDaPGQSWdUh25O5ZkHELT/1r/eOaJyZ6QTSqh8J1/nmG/PpmgW4eKaTV6aanxDQ9KpohlR1gHwc+huQtJOE2PO5SJNBclCuvftSqCeydm7I5Eihgf7L2uy4hzasnqyM1mZNFhBmOU30AdUGomk4h9/4lh+SUVjH00qEXWI8b1QOUqKoLgShrGgaCF0md2379E4c7LvWsKNYFTLKGcjgUSLxr+YdYmJWlki1HquoD1
---
kind: secret
name: gpg_key
data: IAu2WQsFMYm/D2WEX+a0ia80nqpTw0r2rYCSxUd6rZP4jSq2XjdIW6OBlOOAWt5771ZEORYjE/7v9rLXUxixJ3eHI/3vp98thlK6PSyqdrqVGuQBYZjb6z+58Vaks5W/zALAVFgMvwChX6UK3sOqS0eDZPsVxSA5uCNITgSjeAJbilocN6U5+jrSx2vsTeDUgJ0/TGklG2d+oPpKSPQHCU80JVPbnBgzBPIZJlNzTzXkYl72VlUVEt9YKKpmuwsChStYl8i1kkoVwaN64jGSz7SzqTLRrREVKumw9vt3zqoM2OfbULweqG/HZcO1yIcsWHpu7sJ8PCU314jKki9JUMGO1NN9DucgQXApfmYpbrLzlSpT3QD4RYTrbHHPqWtjhZwrUcIN6LJag5TYtkVzc/bnaQ2BsGMc/1UxLT5TdVL+ncKD9vKngIDZRARy1N9yY5tHBPBgbe0YEGmbAimg0VcSzRJU4fkl7Jq6SvDVX3W30hnIuXm+q+Ic+uaAhbrNrj1pcVyQb5ukAX6sv2jdnNAVUnD2HwSE/zYu9Uo6f27V1gYQO+ObVqJi5Y3VaDyB3gcpDfAitTnD6Mfsnnh9Z0kmK3ZDsNAqygaJP/bih2hsKA7hqGpm0EFzSLfZG4dRFdFDEJQZu15hMPxyxABS/Zuxd71p7WBW0tz3P8uwMYi1g7vEgeRva342feU7DbQpGe5RYhhKrRqb3ZZDhiRi499D6DhlN5aTEm8wsYYAtIflqoWJEK1Yy1CRknumOz9jpbyYTnk7PG7v23kE+7tE+FowLRTabI1jVnXJfSyeA4NGpBKvMDVaobVqxHnjMsM1a1F/6tLuGp0H+AZV+92yHzCETgJ76ArUxWZGnbpUyfC5JP+z6OmqJGiFYmqiw3Q0tqUyIp8ENibkusQ9cLnfWQCQ5AY1drKn4IaOFxMrdZMD3bGzTTCGCvAkuDcHNPx7sxFLb9kWouIZiXzV1J28AsidE26jVnLCaC+QSq+7x93eEoA6DnczASx8/mjglGWiG0o0/4h8CpppOmGY2m79fHiBO1HfnjKgsjk+Nz8qgiOXiWdx0q032utg2dyUGUFgNGv65lCKBAZrdF5NJdZvI6g1UybGI/HDMc0nMHok141YXQS4oVHJrxit10L9RPz57BbTJUFSq/M0iVP4ButAtEvxeO/j5fL5AiWUE/p//KBRyffK2Kq3E8Kwe0ywHjLFPtaDedgloxZUB58JS1y6W98YQKz0lUGoQt69sWgH8P2aij8X5588yda3oOnnJiCirSOQpwWg2TdZoJdcur9V8fgLBG2cTtSHRpecbagjpxKN5HHTBoKPifclkKmvO+pDelgmbOWpXZk1Hr6a2rHprMy4bZ69G06Mx0vQqsFq5eoE2kckxFoHsspzOoPeQxbqVRkPd5YljdSgP8t+d9IrF4JZyyVRxG+avSv4+Ri/g6DkLZZtV35xGd55McEMrQs3WpOTv6t1XiId13FA6Fotk/njJaMKxpSukRN6L2h74R80seAUR5mX/0Ra+Whna8yVc+MqC/lZIcfGg7DIebweNkJkr1qxluvWhNgNVZZjX6kXZfM2JNxVRvvGxrHMXelgBrv5fswJjF+9VgTYMGi4uMzpw2OtX4zrPbrR3mUhQfkbiWN9ll6yE5+kBMe2bvLuLbuZEB2iq8ky2g85iYxNc7w0IGu3LHuHI91NqeLOX7L/0sghcgGZ4A4tqkUTbF8r7zn1tvAsZrlcQpqPMsOASvn4htNFwUQtW7ah0XDgeZ4I85ryzGREflaZdFv4xRAodCDDJp3H33/SUYF3ru/GV3YO9vqieZtWITfL4gyhyG4fyF1X47s/MmP1jHy5xfRydvHrCyS+1VuZlVfYdpgizRxd4sNxaK7Ru6HLD6drJp1srroemFxd/qubZRv1SC/QJ+fswaex7MeXSLfLOA14ueUSMYhDLsM2pZFYSI+XL2VhxMj/gjzMRytXbGX+pQjIAGgQR1dCBwhPOmY/qBuGVgZYw0vF97Zi7KAvLvojy0ABY12iWsxYiGAYzx+kFC4/nZ6nrstZMM+8t8QOrJMGSMIxwhWZtn0F/qvG2S95R3ifFwoAwv1J8OEHG0feWrz/azK0EcbFEhVIFdNhaLzNTFquKypu8Sfc6spzwcLKzW+s8BDkGb2fxGRmQ9RnlU/TSgcDBS1iBbRUcY0fQMPPu37mkElUyc1h3OLYTJMSAxRL76um2OsxxjzV3CdJ1eEUMZc38ScYDdm2Hxbdy4BP7nSpDg3EVKE35mHV/rTKfeIK6/XfkHengsvgKGLdwl+nwnoiQDM+ME8Ng0vmCLd6dNoc6z0m73MZz+tSrd5Sl1ubMlaabupfm2jG6GpPRp6xr7LnFFpQB8z8iY0dHyJknptFaB+QylFv7tWAjy/ljEy/+qdmVPQxXhRWCNDsqnOBFkI5F7lpwB+maUpWGKnntLllTYjRoi6D9vjmGrGkWstzUcE+w/9IpHLKPUA/eTWSZSSEXCL4NTuSdqTUftvzNrPQ0J6U8zw49o+Hlg+1iUge/i/Bf9WyTqVLt4n6Mp05tQ1mhzA+LIyAEb/Q6whmoG7EGbXz3t/VPaVTBJRr4ZAuFQF92Zfc2sauwGTuAlMya31HjaY5mdKrQhJZuylI6QRPpb5m6IqT/5Vfuf4w/luLXf7UGOThtRt5rVO3ObCGcU6GbaKJozQcyAUjUa8xd5WBuTR4gFSLoksokn2L0AN0RBac8wIp3YOV2hG5TekZnqalBDCwQCQxsEo3JHdWfvU0PznqFr+FnCEKEzlffgfc8opEMWqUTHyPv8CG5qAf7WITybNk7zH478zfhcFiU32p7DkJrIL0e9ihAzmx9x17niSZb0C0Ft2XmacqxeWB1GKY5U49xg6BpMWkWLQ1lO1nYHnYKcDT8mKdoUWauhCl5/X02edBhD5FK3+TXxFqqtPY9fdQeWeszl+aLXOYl1+yybMsWLLeIqDAlbCKuiRSMoc+oZRtPfPJdr5aM+EdCouH6f8PeuOgx5wF/JWbBvy16wcXUTYUvPQ8a4IdQhy/vYKokGEuiK+pvCyfHcl12o5dNKMwQT9/vwK3KvscV4n/ndQ3CNUwLmFAhD7w4/HZeuMtCvIEEZYvS69KZvjm5vp2a1k/Fw7LNpzCTnE9gUaqhalGVJDT2NyXABxvgnFHq4hGshCpZc86qxYojCmL7l3UgDntfoJMuyBvnew3IeY1Nd/FgtsV1M2AUKyjOiR0jZEbiCtp6Rx2UsetZaPvORpOxI6E+LS40jMyyg6qNmkDe8Yh/TAR+8h9ZdZ+giwnoX23zP40H+4SQau4S7HBKaeyMMuH1DM0z30l8eoZcnRxYpm9VCrXeXR+F5a7GD1gQhJXbRkUxVf1Y9TG0m5Z0Bnq1RN2NdUPGuB0PeenG0QyplPFFpOeVPI9GHYuL5KjpQDW0HaihijExbCbZc+AcoJ+7hU9DDabW5XE+VeSR6f9afmXJzaLA4TKYO/rxnOz7A/oqs7Ip254E4FtCEMlDSGU2fxLiYCOopoXlwp8xwWxoS7Ml5YDZoqZLg7aTGX+a+88DvO11VnBTO2ff8ERoLKi1hoW4aEc0vSgnKpgCJeKe0PUnfP8un2GQgn7jHL4vFub2gfhmWFEPr+ecsMFrkonyhQTNutE5RX3jKjkJyXbOf50I49+6HifMMBaQuTttPRPfRzD6UmBNR/D7qDA/39nRQi2PD3MNLgUjKkDtYh2TLfcnr1H/Voo5PW2wkZkd2pJKS143qf03VSp/XTAv67CA7ugUqEbRXiymNIJWvdJSrNNFRBrzkrkVQrUE8heC49HxC+ireZQmmPYqR4f6Z2oTwXcyEuHZkJXVE2B55nD6Ut/zst3O3RxiRkq7pLZiyyedlBCfiEZ7KfukZ3S15S8DKydoSBC9YoaRXpF5lKtvXyhp3TdsNlcIioFuPxjjQ0jiob2NgtM5WzY3Qu4UrhuLd/IYwlnLCVoVycG1B62YJgUmt+DoARQNO5XoK+2Xr7YrvlmPP8TMrMcBMwer1x8A8FbDFqEHzWv2NQFZS4lLWmPrKk6HfDiKovTto8v+YXEbnQMyU6kV+z450bmbj1WXl1Xl82D8+40fuCSoT37eZjlZzrPcUj1Yiqdy42zC9TNoshzfN0CyExSCIQr9/DtDAb2mk6mhFIJpWE1pg7iE/BjTcq4O+Z2nBYD9iI507GVa7SZAwUldSOAGbxFA9E0nqxtNVAGB3oleyh96YeP8BeqE09NvxWkGkiqM8NhCRzAddlIgzg8IQp3KGf3iE+GNX6KWU3ClX44YqI+VX61WfNauADxqBzhMdI79+32xT3Jq4xtC9h63hgyRBII9FNkc5XVdUJHMG0If8qZLo1MeD6WiNgfRvNrx1ft+bkrvRbzRe7bdsUYGpXCmE2YpK8CoQKVi/DLckCioF9VTOPARdJkc2ctlTJ9uIfueUsAjweiu1wB1w9fGCzo1rea6BO7qBDsV0rWGB7Hhk+NqYE5uSbPfpyPTIwH1g/75DZHsn/7DHGsgBLtPGSKufQw+Z8PY/Pio44Av9urpd1mGxUybsmKyX7v/TZIBS1tRIexamtWc/VL/pyfSdFp3UKxXy2pdhXyRdtKxZzP4G8euKnM44xC4QuiRDKIRUWTR6P6PYHq/hmZ7q4JVkRHHFyZll8xP9frCIrHDtvu20s5NWQ2ZN7ZIax+aubifOx1QDlearl5QZJ6qXyUlVsTzy7GBAkmW1JVFMiBSDw26IR/LrpLexRv2UNEoW29XCBBer84Hc11+V38hW8WrPrASuyYLBZGCHp3FkyPeiaRSAAgffZDw68wQm2+oSJpxrVVtQTouqNAM0syvWNuT9iCW3eOZLP9WNYAIIHQfMyHxQM/PPobJCb1Psc3kYWirOr6F1Cfb9xD3IUv1IU41XWcDF4xxKUa/p2696U0ehZVHTApJRghbPYcev4t1QwIiNpSEOA37zvmd4gq9o3OR2GZb4f9u2ohuIsXGIGpm1Z/rYH8wmT3cR2hQM9cBXdsazsZrAxqBx5HiXJShjyfYUYcvk2mbbQDAGZ3Xpr4jFzKwlPvLV7sUF2+GizkeP3W9rqcRaepKdaKhNW6VI4T3cRICqxUn5Z4MIyXnnIDN5muY1N5+DYtIfb7NPrRrS5xdmjM3RjKlhApUkvSjMvEdTzlvhlN07k8ak6a+X2Wsu/UTLWLN5dYgrfO9g2rg/CG2Uq04fSr971qMGOnBjhEK07Hl5zKjYp+9f/3DPV5W/vE3hqau/dz6jGCsWDLoJHoTVDbP7wmUu9zt/D8eXYT6f5bfCZd+oHtMzP63LI+SpPFFFaezcotxRp75RTsSU2YBOrPLiQEGywO4kh65tLvdiwoUuhIUlkRWUdTEIIZb0Lu6EYR44bUG+nrilU0RrpARXwKJ56bwd3TqIVe07UuCut5vcee+6Vgba+YaBHViAI3oU8oNRHjVUoJp41ppVLIis67C6jUXLpZbEJccjDDtV8elvbcgOb6ibrGdD2XTrnW+Q8oGr1yXmJCOOVz9+h4IICSfvV8gAcg09N+8kh06tQbTVnZucc8lVslmQgjgthe/oqjJP054AfoghOC87p4wCVM522yiljvmN3iwKreVCwgCXEaYaMEmja9ZL7ZEQmc5LLyJHOexEYlx4lCZS9B9A5HlP4cHXQDYoSHg7yfeVXKgPcgxhjuAJORodI9Ey/0cvKGrD/ZB8A46CtNe4yn/dhQxMya9IgBo9mfk3QMOZTnD4UwSn5hEMrK5v8AHSSgVQh56dCFPYBv9WsB9kfjLZpBeHhO0gOTAS1dohkXI88YP3TGr3g72SOvFZiV739WfgSM7UKLbq1AjtrwuxoGJEKZdn0cYlQf/lge1BHnrcPa0puay3H9R2dvV747RTBdUkmwBx05Y1WFMdRRzcjloEwUMUx5q6Qo7G1BA+s5j1MENz2FyfaCGGC7uTqKLVNe9Iy2zpIbRZWPAaCHIXOHXJgPdrw9HU4LpANL8zGEAaCmUFLU+mEolECFcmxbkumHt13ALstdv9aFzcndKGFIWphlfKtvwlMNEq9nv00+A+J2x1ctwyY+Zqh03swY1sSC+fe34YTOhLC7pVazm2rdThrftLjf3gxE1rWevtZk8vwqR5joaJSHHYkF+Esa1r+6YEW/sbIxN1qNgrPbx+PwcXC9dkP23zcdU3Sn4BuEDH1Brm7jjOxtc1BW2KK5i9YKNDAmNAy+5H+siPWY8eUsoz2aPXwhLZtpd3G/qRyftUojzji8/3ew0EbO9XdXe7PwVsIHMqxrGodPz5/2+C8iRJySlSS6a8008idAbdNE8SyqH677QoA9Ygz2a67/kKDiYpDRkAoJ+SjMSd/VLrmTVwXMWgU0URuFK5aj3QZOGEC4kkmZiWF6RAZA5miLFc2Zd5suzu0EuL3s8hlbit1fFlNHu8jONoURcRBeb4HJYPY83/8UQ4nugc+V3uvIX/Ko8qzVP7IxcVHT25TIi2bEG55ismxR/BvuXM6SRwTWZo1ll2QwvTak5/NSS8tTVhlZ8CJQpJx47XxjHaKTE5j+WcndpGZUZH68tnDmLgIWsPKeQGjIqfC+Op/zT5//LhIBmq6ldUtpO3NDOxAysiVG+kFmA0JrCoIKyWkKRonmoSRe1E4kxaTt/1BaNWbvEVRwROi+mXYOhLGv6EJ05eI3MEfMBwJJug9oUj9TVw==
---
kind: signature
hmac: 1ca7239c18585f14776aaddb0bb56d3add8653cc2cab0fc4008c1742a511eab2

...
